ERROR - 2024-05-16 08:31:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:31:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:32:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:32:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:33:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:33:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:35:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:35:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:35:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:35:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:35:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:35:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:36:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:36:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:36:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:36:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:36:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:36:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: users]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 08:36:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\attoinfotech\system\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#4 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
#5 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
#6 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->index()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-05-16 08:36:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1713): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `users`', [], false)
 3 SYSTEMPATH\Model.php(667): CodeIgniter\Database\BaseBuilder->countAllResults(false)
 4 SYSTEMPATH\BaseModel.php(1284): CodeIgniter\Model->countAllResults(false)
 5 APPPATH\Controllers\Users.php(24): CodeIgniter\BaseModel->paginate(5)
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 09:00:06 --> Error: Undefined constant "addressIndex"
[Method: POST, Route: users/create]
in APPPATH\Views\users\create.php on line 48.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/create', [], true)
 4 APPPATH\Controllers\Users.php(65): view('users/create')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 09:02:36 --> Error: Undefined constant "addressIndex"
[Method: POST, Route: users/create]
in APPPATH\Views\users\create.php on line 48.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/create', [], true)
 4 APPPATH\Controllers\Users.php(65): view('users/create')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:30:52 --> Error: Undefined constant "addressIndex"
[Method: GET, Route: users/create]
in APPPATH\Views\users\create.php on line 48.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/create', [], true)
 4 APPPATH\Controllers\Users.php(65): view('users/create')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:36:59 --> Error: Undefined constant "addressIndex"
[Method: POST, Route: users/create]
in APPPATH\Views\users\create.php on line 48.
 1 SYSTEMPATH\View\View.php(234): include()
 2 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/create', [], true)
 4 APPPATH\Controllers\Users.php(65): view('users/create')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:37:21 --> ErrorException: Undefined variable $users
[Method: POST, Route: users/create]
in APPPATH\Views\users\index.php on line 34.
 1 APPPATH\Views\users\index.php(34): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $users', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 34)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(65): view('users/index')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 13:42:53 --> mysqli_sql_exception: Unknown column 'user_id' in 'field list' in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `ad...', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ad...')
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ad...')
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(1821): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ad...', NULL, false)
#4 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(2210): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\attoinfotech\system\Model.php(417): CodeIgniter\Database\BaseBuilder->insertBatch(Array, NULL, 100)
#6 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(960): CodeIgniter\Model->doInsertBatch(Array, NULL, 100, false)
#7 C:\xampp\htdocs\attoinfotech\app\Models\AddressModel.php(20): CodeIgniter\BaseModel->insertBatch(Array)
#8 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(61): App\Models\AddressModel->createAddressBatch(Array)
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->create()
#10 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#11 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 {main}
CRITICAL - 2024-05-16 13:42:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
[Method: POST, Route: users/create]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(1821): CodeIgniter\Database\BaseConnection->query('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)', null, false)
 2 SYSTEMPATH\Database\BaseBuilder.php(2210): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
 3 SYSTEMPATH\Model.php(417): CodeIgniter\Database\BaseBuilder->insertBatch([...], null, 100)
 4 SYSTEMPATH\BaseModel.php(960): CodeIgniter\Model->doInsertBatch([...], null, 100, false)
 5 APPPATH\Models\AddressModel.php(20): CodeIgniter\BaseModel->insertBatch([...])
 6 APPPATH\Controllers\Users.php(61): App\Models\AddressModel->createAddressBatch([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:42:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)')
 3 SYSTEMPATH\Database\BaseBuilder.php(1821): CodeIgniter\Database\BaseConnection->query('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)', null, false)
 4 SYSTEMPATH\Database\BaseBuilder.php(2210): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
 5 SYSTEMPATH\Model.php(417): CodeIgniter\Database\BaseBuilder->insertBatch([...], null, 100)
 6 SYSTEMPATH\BaseModel.php(960): CodeIgniter\Model->doInsertBatch([...], null, 100, false)
 7 APPPATH\Models\AddressModel.php(20): CodeIgniter\BaseModel->insertBatch([...])
 8 APPPATH\Controllers\Users.php(61): App\Models\AddressModel->createAddressBatch([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:42:53 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1821): CodeIgniter\Database\BaseConnection->query('INSERT INTO `addresses` (`address`, `city`, `pincode`, `state`, `user_id`)
VALUES (\'Mirza dighu yadav chawl, goandevi road,\',\'mumbai\',\'400101\',\'Maharashtra\',1)', null, false)
 5 SYSTEMPATH\Database\BaseBuilder.php(2210): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
 6 SYSTEMPATH\Model.php(417): CodeIgniter\Database\BaseBuilder->insertBatch([...], null, 100)
 7 SYSTEMPATH\BaseModel.php(960): CodeIgniter\Model->doInsertBatch([...], null, 100, false)
 8 APPPATH\Models\AddressModel.php(20): CodeIgniter\BaseModel->insertBatch([...])
 9 APPPATH\Controllers\Users.php(61): App\Models\AddressModel->createAddressBatch([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->create()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:42:58 --> ErrorException: Undefined array key "id"
[Method: GET, Route: users]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:01 --> ErrorException: Undefined array key "id"
[Method: GET, Route: users]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:19 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:19 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:27 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:31 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:51 --> ErrorException: Undefined array key "id"
[Method: GET, Route: users]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:43:56 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:44:03 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:47:37 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:47:39 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:48:51 --> ErrorException: Undefined array key "id"
[Method: GET, Route: /]
in APPPATH\Views\users\index.php on line 43.
 1 APPPATH\Views\users\index.php(43): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "id"', 'C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php', 43)
 2 SYSTEMPATH\View\View.php(234): include('C:\\xampp\\htdocs\\attoinfotech\\app\\Views\\users\\index.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('users/index', [], true)
 5 APPPATH\Controllers\Users.php(27): view('users/index', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->index()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-05-16 13:51:01 --> mysqli_sql_exception: Unknown column 'user_id' in 'where clause' in C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp\htdocs\attoinfotech\system\Database\MySQLi\Connection.php(308): mysqli->query('DELETE FROM `ad...', 0)
#1 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `ad...')
#2 C:\xampp\htdocs\attoinfotech\system\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `ad...')
#3 C:\xampp\htdocs\attoinfotech\system\Database\BaseBuilder.php(2823): CodeIgniter\Database\BaseConnection->query('DELETE FROM `ad...', Array, false)
#4 C:\xampp\htdocs\attoinfotech\system\Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
#5 C:\xampp\htdocs\attoinfotech\system\BaseModel.php(1158): CodeIgniter\Model->doDelete(NULL, false)
#6 C:\xampp\htdocs\attoinfotech\app\Controllers\Users.php(106): CodeIgniter\BaseModel->delete()
#7 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(933): App\Controllers\Users->delete('1')
#8 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#9 C:\xampp\htdocs\attoinfotech\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\attoinfotech\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\attoinfotech\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\attoinfotech\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-05-16 13:51:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
[Method: GET, Route: users/delete/1]
in SYSTEMPATH\Database\BaseConnection.php on line 676.
 1 SYSTEMPATH\Database\BaseBuilder.php(2823): CodeIgniter\Database\BaseConnection->query('DELETE FROM `addresses`
WHERE `user_id` = :user_id:', [...], false)
 2 SYSTEMPATH\Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 3 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 4 APPPATH\Controllers\Users.php(106): CodeIgniter\BaseModel->delete()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->delete('1')
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:51:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `addresses`
WHERE `user_id` = \'1\'')
 2 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `addresses`
WHERE `user_id` = \'1\'')
 3 SYSTEMPATH\Database\BaseBuilder.php(2823): CodeIgniter\Database\BaseConnection->query('DELETE FROM `addresses`
WHERE `user_id` = :user_id:', [...], false)
 4 SYSTEMPATH\Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 5 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 6 APPPATH\Controllers\Users.php(106): CodeIgniter\BaseModel->delete()
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->delete('1')
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-16 13:51:01 --> [Caused by] mysqli_sql_exception: Unknown column 'user_id' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('DELETE FROM `addresses`
WHERE `user_id` = \'1\'', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute('DELETE FROM `addresses`
WHERE `user_id` = \'1\'')
 3 SYSTEMPATH\Database\BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery('DELETE FROM `addresses`
WHERE `user_id` = \'1\'')
 4 SYSTEMPATH\Database\BaseBuilder.php(2823): CodeIgniter\Database\BaseConnection->query('DELETE FROM `addresses`
WHERE `user_id` = :user_id:', [...], false)
 5 SYSTEMPATH\Model.php(510): CodeIgniter\Database\BaseBuilder->delete()
 6 SYSTEMPATH\BaseModel.php(1158): CodeIgniter\Model->doDelete(null, false)
 7 APPPATH\Controllers\Users.php(106): CodeIgniter\BaseModel->delete()
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Users->delete('1')
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
